Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Сельков Вадим Андреевич
- АИС-22-1

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |
| Задание 6 | - | - |
| Задание 7 | - | - |
| Задание 8 | - | - |
| Задание 9 | - | - |
| Задание 10 | - | - |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи. P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.

```python

from functools import lru_cache


@lru_cache(maxsize=128)
def fibonacci(n):
  if n == 0:
    return n
  elif n == 1:
    return 1
  return fibonacci(n - 1) + fibonacci(n - 2)


if __name__ == "__main__":
  print(fibonacci(100))

```
### Результат.
![](pic/10.1.png)

## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

```python

def check(input_func):
  def output_func(*args):
    name, age = args[0], args[1]

    if age < 0 or age > 130:
      age = 'Неккоректный возраст'
    
    return input_func(name, age)

  return output_func

  
@check 
def personal_info(name, age):
  print(f"Имя: {name}, Возраст: {age}")


if __name__ == '__main__':
  personal_info('Владимир', -5)
  personal_info('Вадим', 20)
  personal_info('Мария', 139, 1, 51)


```
### Результат.
![](pic/10.2.png)

## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

```python

def data(*args):
  try: 
    for i in range(len(args[0])):
      try:
        result = (args[0][i] * 15) // 10
        print(result)
      except Exception as ex:
        print(ex)
  except Exception as ex:
    print(ex)
  finally:
    print('Всё обработано')


data([1, 15, 'Fia', 'gag', 'asfa', 51, 2])

```
### Результат.
![](pic/10.3.png)

## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”

```python

class NegativeValueException(Exception):
  pass


def check_name(name):
  if len(name) > 10:
    raise NegativeValueException('Длина более 10 символов')
  else:
    print('Успешная регестрация')


check_name('239193193')
print("-"*40)
check_name('239193193149')

```
### Результат.
![](pic/10.4.png)

## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python

class SiteChecker:
  def __init__(self, func):
    print('> Класс SiteChecker метод __init__ запущен')
    self.func = func

  
  def __call__(self):
    print('> Проверка', self.func.__name__)
    self.func()
    print('> Проверка')


@SiteChecker
def site():
  print('Работа сайта')


print('>> Сайт запущен')
site()
print('>> Сайт выключен')

```
### Результат.
![](pic/10.5.png)

## Самостоятельная работа 1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.

```python

import time

def time_decorator(func):
    def wrapper(*args):
        start_time = time.time()  
        result = func(*args)  
        end_time = time.time()  
        execution_time = end_time - start_time  
        print(f"Время выполнения функции '{func.__name__}': {execution_time:.6f} секунд")
        return result  
    return wrapper

@time_decorator
def fibonacci():
    fib1 = fib2 = 1
    
    for i in range(2, 200):
      fib1, fib2 = fib2, fib1 + fib2
      print(f'{fib2}\n', end='')


if __name__ == '__main__':
  fibonacci()

```

### Результат.

![](pic/10.11.png)

## Вывод

В данной задаче я самостоятельно разобрался с тем, как создать декоратор и "соотвественно" вызвать его в своём коде. А также вспомнил о существовании модуля time.

## Самостоятельная работа 2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python

try:
    with open("empty.txt", "r") as f:
        result = f.read()

    if not result:  
        print("Файл пустой")
    else:
        print(
            f"Содержимое файла:\n"
            f"{result}"
              )
        

except Exception as e:
    print(f"Произошла ошибка: {e}")  

```

### Результат.

![](pic/10.12.png)
![](pic/10.12_1.png)
![](pic/10.12_2.png)

## Вывод

В данной программе я самостоятельно воспользовался функциями try/except.

## Самостоятельная работа 3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python

def summa():
    try:
        n = input("Введите число: ")
        number = float(n) 
        result = 2 + number
        print(f"Результат: {result}")
    except ValueError: 
        print("Неподходящий тип данных. Ожидалось число.")


summa()

```

### Результат.

![](pic/10.13.png)

## Вывод

В данной программе я ознакомился со многими существующими видами исключений в python и подобрал правильное для неподходящего типа данных. 

## Самостоятельная работа 4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python

def announce(func):
    """
    Декоратор announce принимает функцию func в качестве аргумента.
    """
    def wrapper(n):
        """
        Эта функция оборачивает вызов оригинальной функции и добавляет вывод сообщений.
        """
        print(f'Начинаем выполнение функции: {func.__name__}')
        result = func(n)  # Декоратор вызывает оригинальную функцию и возвращает ее результат.
        print(f'Завершено выполнение функции: {func.__name__}')
        return result
    return wrapper


@announce
def say_hello(name):
    print(f"Привет, {name}!")


say_hello('Вадим')

```

### Результат.

![](pic/10.14.png)

## Вывод

В данной программе я придумал свой первый собственный декоратор и пояснил все действия программы в комментариях. 

## Самостоятельная работа 5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python

class NegativeNumberError(Exception):
    """Исключение, возникающее при вводе отрицательного числа."""
    def __init__(self, number):
        super().__init__(f"Ошибка: {number} - это отрицательное число. Пожалуйста, введите положительное число.")
        self.number = number


def check_positive_number(number):
    """Проверяет, является ли число положительным."""
    if number < 0:
        raise NegativeNumberError(number)  # Вызываем исключение, если число отрицательное
    print(f"{number} - это положительное число.")

def main():
    try:
        number = float(input("Введите число: "))  # Запрашиваем число у пользователя
        check_positive_number(number)  # Проверяем число
    except NegativeNumberError as e:
        print(e)  # Обрабатываем исключение и выводим сообщение
    except ValueError:
        print("Ошибка: Пожалуйста, введите корректное число.")

if __name__ == "__main__":
    main()

```

### Результат.

![](pic/10.15.png)

## Вывод

В данном задании я впервые создал свое собственное исключение благодаря тому, что создал отдельный класс. Также пояснения работы этого кода находятся в комментариях.

## Общие выводы по теме

В данной теме я усвоил, что декораторы являются мощным инструментов для модификации поведения функций и методов. Они позволяют добавлять дополнительные функциональные возможности к уже существующим функциям без изменения их кода. 

Также я подробнее ознакомился с обработками исключений. Исключения в Python позволяют работать с ошибками, что, в свою очередь, улучшает надежность кода и его откладку.

Благодаря созданию своих собственных исключений и декораторов надежнее разобрался в предоставленной теме.

